config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'
  resources :messages
  devise_for :users
  resources :rooms
  get 'home/index'
  resources :users, only: [:show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
 root "rooms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  broadcasts_to ->(room) { :message_list}
end

app/models/room.rb
class Room < ApplicationRecord

  has_many :messages

  broadcasts_to ->(room) { :rooms}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :messages
         has_many :rooms

         broadcasts_to ->(room) { :users}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    @messages = Message.all
    # Remove the current user from the list of users

  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  # GET /messages or /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message.room, notice: "" }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to message_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:text, :user_id, :touser, :room_id, :name)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]
before_action :authenticate_user!
  # GET /rooms or /rooms.json
  def index
    @users = User.all

    @messages = Message.all
    @rooms = Room.all

  @rooms = Room.where(user_id: current_user.id).or(Room.where(seconduser_id: current_user.id))

  end

  # GET /rooms/1 or /rooms/1.json
  def show

    @users = User.all
    @message = @room.messages.build
    @messages = Message.includes(:users)

  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy
    @room.messages.each do |message|
      message.destroy
    end
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name, :user_id, :seconduser_id, :email, :secondemail)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    
    @user = User.find(params[:id])
    @room = @user.rooms.build

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/home/index.html.erb
<h1> Users </h1>
<% @users.each do |user| %>
  <p> <%= user.email %> </p>
<% end %>
<% if current_user %>
  <%= render "messages/form", message: @message %>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path %>
  <%= link_to "Sign in", new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Discordclone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%# Simple CSS %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple-v1.css">
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>
      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_field :text %>
  </div>
  <div>
    <%= form.text_field :room_id, type:"hidden"%>
  </div>
  <div>
    <%= form.text_field :user_id, type: "hidden", value: current_user.id %>
  </div>
  <div>
    <%= form.text_field :name, value: current_user.email, type: "hidden" %>
  </div>
  <div>
    <%= form.submit "Send Message"%>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div id="<%= dom_id message %>" style=" ">
  <p> <%= message.name %> </p>
  <p> <%= message.text %> </p>
</div>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Show this message", @message %> |
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Messages</h1>
<div id="messages">
  <% @messages.each do |message| %>
    <%= render message %>
    <p>
      <%= link_to "Show this message", message %>
    </p>
  <% end %>
</div>
<%= link_to "New message", new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>
<%= render "form", message: @message %>
<br>
<div>
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @message %>
<div>
  <%= link_to "Edit this message", edit_message_path(@message) %> |
  <%= link_to "Back to messages", messages_path %>
  <%= button_to "Destroy this message", @message, method: :delete %>
</div>

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>
      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.text_field :user_id, type: "hidden", value: current_user.id %>
  </div>
  <div>
    <%= form.text_field :seconduser_id, style: "display: block", value: @user.id, type: "hidden" %>
  </div>
  <div>
    <%= form.text_field :email, style: "display: block", value: current_user.email, type: "hidden" %>
  </div>
  <div>
    <%= form.text_field :secondemail, style: "display: block", value: @user.email, type: "hidden" %>
  </div>
  <div>
    <%= form.submit "Message this User"%>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>" style="box-shadow: rgba(0, 0, 0, 0.4) 0px 4px 12px; padding: 15px; position: relative;">
  <p style="font-size: 20px; font-weight: bold; margin: 0px; padding: 0px;"> <%= room.secondemail %> </p>
  <p style="font-size: 20px; font-weight: bold; margin: 0px; padding: 0px;"> <%= room.email %> </p>
  <p>
    <%= link_to "", room, style:"position: absolute; left: 0px; top: 0px; height: 100%; width: 100%;"%>
  </p>
</div>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Show this room", @room %> |
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Direct Messages</h1>
<%= turbo_stream_from "rooms"%>
<div id="rooms">
  <% @rooms.each do |room| %>
    <%= render room %>
  <% end %>
</div>
<%= turbo_stream_from "users"%>
<div id="users">
  <h1> Users </h1>
  <%= render @users%>
</div>
<% if current_user %>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path %>
  <%= link_to "Sign in", new_user_session_path %>
<% end %>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/show.html.erb
  <%= link_to "Back to rooms", rooms_path %>
<p style="color: green"><%= notice %></p>
<%= render @room %>
<%= button_to "Destroy this room", @room, method: :delete %>
</div>
<%= turbo_stream_from "message_list"%>
<div style="height: 400px; overflow-y: scroll; " id="messages">
  <% @room.messages.each do |message|%>
    <%= render message %><% end %>
</div>
<div>
  <%= render "messages/form", message: @message %>
  <script>
    const scrollToBottom = (id) => {
    const element = document.getElementById(id);
    element.scrollTop = element.scrollHeight;
    }
    scrollToBottom('messages');
  </script>

app/views/users/_user.html.erb
<p style="font-size: 24px;"> <%= link_to user.email, user %> </p>

app/views/users/show.html.erb
<p style="font-size: 30px;"> <%= @user.email %> </p>
<%= render "rooms/form", room: @room %>